import {
  DeskThing as DK,
  SettingsMultiSelect,
  SettingsNumber,
  SettingsSelect,
  SocketData,
} from 'deskthing-server';
const DeskThing = DK.getInstance();
export { DeskThing }; // Required export of this exact name for the server to connect
import SportsHubService from './sportsHub';

const start = async () => {
  const sportsHub = SportsHubService.getInstance();
  let Data = await DeskThing.getData();
  DeskThing.on('data', (newData) => {
    // Syncs the data with the server
    Data = newData;
    if (Data) {
      sportsHub.updateData(Data);
    }
  });

  // This is how to add settings (implementation may vary)
  if (!Data?.settings?.refreshInterval) {
    setupSettings();
  }

  const handleGet = async (request: SocketData) => {
    if (request.request === 'sportshub_data') {
      DeskThing.sendLog('Getting Sports Hub data');
      const sportsData = await sportsHub.getSportsHub();
      if (sportsData) {
        DeskThing.sendDataToClient({
          type: 'sportshub_data',
          payload: sportsData,
        });
      } else {
        console.warn('Error getting Sports Hub data');
      }
    }
  };

  DeskThing.on('get', handleGet);
  const stop = async () => {
    sportsHub.stop();
  };
  DeskThing.on('stop', stop);
};

const setupSettings = async () => {
  const refreshIntervalSetting: SettingsNumber = {
    label: 'Refresh Interval (minutes)',
    description: 'The amount of minutes between each refresh.',
    type: 'number',
    value: 1,
    max: 60,
    min: 1,
  };

  const favoriteLeagueSetting: SettingsSelect = {
    label: 'Favorite League',
    description: 'Select your favorite league.',
    value: 'NONE',
    type: 'select',
    options: [
      { label: 'None', value: 'NONE' },
      { label: 'NFL', value: 'NFL' },
      { label: 'NBA', value: 'NBA' },
      { label: 'NHL', value: 'NHL' },
      { label: 'MLB', value: 'MLB' },
      { label: 'MLS', value: 'MLS' },
      { label: 'Serie A', value: 'SerieA' },
      { label: 'LaLiga', value: 'LaLiga' },
      { label: 'Champions League', value: 'ChampionsLeague' },
      { label: 'Premier League', value: 'PremierLeague' },
      { label: 'Bundesliga', value: 'Bundesliga' },
      { label: 'NCAAF', value: 'NCAAF' },
    ],
  };

  const leaguesToShowSetting: SettingsMultiSelect = {
    label: 'Leagues To Show',
    description: 'Select the leagues you want to display.',
    value: [],
    type: 'multiselect',
    options: [
      { label: 'NFL', value: 'NFL' },
      { label: 'NBA', value: 'NBA' },
      { label: 'NHL', value: 'NHL' },
      { label: 'MLB', value: 'MLB' },
      { label: 'MLS', value: 'MLS' },
      { label: 'Serie A', value: 'SerieA' },
      { label: 'LaLiga', value: 'LaLiga' },
      { label: 'Champions League', value: 'ChampionsLeague' },
      { label: 'Premier League', value: 'PremierLeague' },
      { label: 'Bundesliga', value: 'Bundesliga' },
      { label: 'NCAAF', value: 'NCAAF' },
    ],
  };

  const favoriteNBATeamsSetting: SettingsMultiSelect = {
    label: 'Favorite NBA Teams',
    description: 'Select your favorite NBA Football teams.',
    value: [],
    type: 'multiselect',
    options: [
      { label: 'Atlanta Hawks', value: 'ATL' },
      { label: 'Brooklyn Nets', value: 'BKN' },
      { label: 'Boston Celtics', value: 'BOS' },
      { label: 'Charlotte Hornets', value: 'CHA' },
      { label: 'Chicago Bulls', value: 'CHI' },
      { label: 'Cleveland Cavaliers', value: 'CLE' },
      { label: 'Dallas Mavericks', value: 'DAL' },
      { label: 'Denver Nuggets', value: 'DEN' },
      { label: 'Detroit Pistons', value: 'DET' },
      { label: 'Golden State Warriors', value: 'GSW' },
      { label: 'Houston Rockets', value: 'HOU' },
      { label: 'Indiana Pacers', value: 'IND' },
      { label: 'Los Angeles Clippers', value: 'LAC' },
      { label: 'Los Angeles Lakers', value: 'LAL' },
      { label: 'Memphis Grizzlies', value: 'MEM' },
      { label: 'Miami Heat', value: 'MIA' },
      { label: 'Milwaukee Bucks', value: 'MIL' },
      { label: 'Minnesota Timberwolves', value: 'MIN' },
      { label: 'New Orleans Pelicans', value: 'NOH' },
      { label: 'New York Knicks', value: 'NYK' },
      { label: 'Oklahoma City Thunder', value: 'OKC' },
      { label: 'Orlando Magic', value: 'ORL' },
      { label: 'Philadelphia 76ers', value: 'PHI' },
      { label: 'Phoenix Suns', value: 'PHO' },
      { label: 'Portland Trail Blazers', value: 'POR' },
      { label: 'Sacramento Kings', value: 'SAC' },
      { label: 'San Antonio Spurs', value: 'SAS' },
      { label: 'Toronto Raptors', value: 'TOR' },
      { label: 'Utah Jazz', value: 'UTH' },
      { label: 'Washington Wizards', value: 'WAS' },
    ],
  };

  const favoriteNFLTeamsSetting: SettingsMultiSelect = {
    label: 'Favorite NFL Teams',
    description: 'Select your favorite NFL Football teams.',
    value: [],
    type: 'multiselect',
    options: [
      { label: 'Arizona Cardinals', value: 'ARI' },
      { label: 'Atlanta Falcons', value: 'ATL' },
      { label: 'Baltimore Ravens', value: 'BAL' },
      { label: 'Buffalo Bills', value: 'BUF' },
      { label: 'Carolina Panthers', value: 'CAR' },
      { label: 'Chicago Bears', value: 'CHI' },
      { label: 'Cincinnati Bengals', value: 'CIN' },
      { label: 'Cleveland Browns', value: 'CLE' },
      { label: 'Dallas Cowboys', value: 'DAL' },
      { label: 'Denver Broncos', value: 'DEN' },
      { label: 'Detroit Lions', value: 'DET' },
      { label: 'Green Bay Packers', value: 'GB' },
      { label: 'Houston Texans', value: 'HOU' },
      { label: 'Indianapolis Colts', value: 'IND' },
      { label: 'Jacksonville Jaguars', value: 'JAX' },
      { label: 'Kansas City Chiefs', value: 'KC' },
      { label: 'Miami Dolphins', value: 'MIA' },
      { label: 'Minnesota Vikings', value: 'MIN' },
      { label: 'New England Patriots', value: 'NE' },
      { label: 'New Orleans Saints', value: 'NO' },
      { label: 'New York Giants', value: 'NYG' },
      { label: 'New York Jets', value: 'NYJ' },
      { label: 'Las Vegas Raiders', value: 'LV' },
      { label: 'Philadelphia Eagles', value: 'PHI' },
      { label: 'Pittsburgh Steelers', value: 'PIT' },
      { label: 'Los Angeles Chargers', value: 'LAC' },
      { label: 'San Francisco 49ers', value: 'SF' },
      { label: 'Seattle Seahawks', value: 'SEA' },
      { label: 'Los Angeles Rams', value: 'LAR' },
      { label: 'Tampa Bay Buccaneers', value: 'TB' },
      { label: 'Tennessee Titans', value: 'TEN' },
      { label: 'Washington Commanders', value: 'WAS' },
    ],
  };

  const favoriteNHLTeamsSetting: SettingsMultiSelect = {
    label: 'Favorite NHL Teams',
    description: 'Select your favorite NHL teams.',
    value: [],
    type: 'multiselect',
    options: [
      { label: 'Anaheim Ducks', value: 'ANA' },
      { label: 'Boston Bruins', value: 'BOS' },
      { label: 'Buffalo Sabres', value: 'BUF' },
      { label: 'Calgary Flames', value: 'CGY' },
      { label: 'Carolina Hurricanes', value: 'CAR' },
      { label: 'Chicago Blackhawks', value: 'CHI' },
      { label: 'Colorado Avalanche', value: 'COL' },
      { label: 'Columbus Blue Jackets', value: 'CBJ' },
      { label: 'Dallas Stars', value: 'DAL' },
      { label: 'Detroit Red Wings', value: 'DET' },
      { label: 'Edmonton Oilers', value: 'EDM' },
      { label: 'Florida Panthers', value: 'FLA' },
      { label: 'Los Angeles Kings', value: 'LAK' },
      { label: 'Minnesota Wild', value: 'MIN' },
      { label: 'Montreal Canadiens', value: 'MTL' },
      { label: 'Nashville Predators', value: 'NSH' },
      { label: 'New Jersey Devils', value: 'NJD' },
      { label: 'New York Islanders', value: 'NYI' },
      { label: 'New York Rangers', value: 'NYR' },
      { label: 'Ottawa Senators', value: 'OTT' },
      { label: 'Philadelphia Flyers', value: 'PHI' },
      { label: 'Pittsburgh Penguins', value: 'PIT' },
      { label: 'San Jose Sharks', value: 'SJS' },
      { label: 'Seattle Kraken', value: 'SEA' },
      { label: 'St. Louis Blues', value: 'STL' },
      { label: 'Tampa Bay Lightning', value: 'TBL' },
      { label: 'Toronto Maple Leafs', value: 'TOR' },
      { label: 'Vancouver Canucks', value: 'VAN' },
      { label: 'Vegas Golden Knights', value: 'VGK' },
      { label: 'Washington Capitals', value: 'WSH' },
      { label: 'Winnipeg Jets', value: 'WPG' },
    ],
  };

  const favoriteMLBTeamsSetting: SettingsMultiSelect = {
    label: 'Favorite MLB Teams',
    description: 'Select your favorite Major League Baseball teams.',
    value: [],
    type: 'multiselect',
    options: [
      { label: 'Arizona Diamondbacks', value: 'ARI' },
      { label: 'Atlanta Braves', value: 'ATL' },
      { label: 'Baltimore Orioles', value: 'BAL' },
      { label: 'Boston Red Sox', value: 'BOS' },
      { label: 'Chicago Cubs', value: 'CHC' },
      { label: 'Chicago White Sox', value: 'CWS' },
      { label: 'Cincinnati Reds', value: 'CIN' },
      { label: 'Cleveland Guardians', value: 'CLE' },
      { label: 'Colorado Rockies', value: 'COL' },
      { label: 'Detroit Tigers', value: 'DET' },
      { label: 'Houston Astros', value: 'HOU' },
      { label: 'Kansas City Royals', value: 'KC' },
      { label: 'Los Angeles Angels', value: 'LAA' },
      { label: 'Los Angeles Dodgers', value: 'LAD' },
      { label: 'Miami Marlins', value: 'MIA' },
      { label: 'Milwaukee Brewers', value: 'MIL' },
      { label: 'Minnesota Twins', value: 'MIN' },
      { label: 'New York Mets', value: 'NYM' },
      { label: 'New York Yankees', value: 'NYY' },
      { label: 'Oakland Athletics', value: 'OAK' },
      { label: 'Philadelphia Phillies', value: 'PHI' },
      { label: 'Pittsburgh Pirates', value: 'PIT' },
      { label: 'San Diego Padres', value: 'SD' },
      { label: 'San Francisco Giants', value: 'SF' },
      { label: 'Seattle Mariners', value: 'SEA' },
      { label: 'St. Louis Cardinals', value: 'STL' },
      { label: 'Tampa Bay Rays', value: 'TB' },
      { label: 'Texas Rangers', value: 'TEX' },
      { label: 'Toronto Blue Jays', value: 'TOR' },
      { label: 'Washington Nationals', value: 'WAS' },
    ],
  };

  const selectedNCAAFTeamsSetting: SettingsMultiSelect = {
    label: 'NCAA Football Teams',
    description:
      'Select your favorite NCAA Football teams to display. (Only selected teams will be displayed)',
    value: [],
    type: 'multiselect',
    options: [
      { label: 'Boston College', value: 'BC' },
      { label: 'Clemson', value: 'CLEM' },
      { label: 'Duke', value: 'DUKE' },
      { label: 'Florida State', value: 'FSU' },
      { label: 'Georgia Tech', value: 'GT' },
      { label: 'Louisville', value: 'LOU' },
      { label: 'Miami (FL)', value: 'MIA' },
      { label: 'NC State', value: 'NCST' },
      { label: 'Pittsburgh', value: 'PITT' },
      { label: 'Syracuse', value: 'SYR' },
      { label: 'North Carolina', value: 'UNC' },
      { label: 'Virginia', value: 'UVA' },
      { label: 'Virginia Tech', value: 'VT' },
      { label: 'Wake Forest', value: 'WAKE' },
      { label: 'Illinois', value: 'ILL' },
      { label: 'Indiana', value: 'IND' },
      { label: 'Iowa', value: 'IOWA' },
      { label: 'Michigan', value: 'MICH' },
      { label: 'Michigan State', value: 'MSU' },
      { label: 'Minnesota', value: 'MINN' },
      { label: 'Nebraska', value: 'NEB' },
      { label: 'Northwestern', value: 'NW' },
      { label: 'Ohio State', value: 'OSU' },
      { label: 'Penn State', value: 'PSU' },
      { label: 'Purdue', value: 'PUR' },
      { label: 'Rutgers', value: 'RUTG' },
      { label: 'Maryland', value: 'UMD' },
      { label: 'Wisconsin', value: 'WIS' },
      { label: 'Baylor', value: 'BAY' },
      { label: 'Iowa State', value: 'ISU' },
      { label: 'Kansas', value: 'KU' },
      { label: 'Kansas State', value: 'KSU' },
      { label: 'Oklahoma', value: 'OKLA' },
      { label: 'Oklahoma State', value: 'OKST' },
      { label: 'TCU', value: 'TCU' },
      { label: 'Texas', value: 'TEX' },
      { label: 'Texas Tech', value: 'TTU' },
      { label: 'West Virginia', value: 'WVU' },
      { label: 'Arizona', value: 'ARIZ' },
      { label: 'Arizona State', value: 'ASU' },
      { label: 'Cal', value: 'CAL' },
      { label: 'Colorado', value: 'COLO' },
      { label: 'Oregon', value: 'ORE' },
      { label: 'Oregon State', value: 'ORST' },
      { label: 'Stanford', value: 'STAN' },
      { label: 'UCLA', value: 'UCLA' },
      { label: 'USC', value: 'USC' },
      { label: 'Utah', value: 'UTAH' },
      { label: 'Washington', value: 'WASH' },
      { label: 'Washington State', value: 'WSU' },
      { label: 'Alabama', value: 'ALA' },
      { label: 'Arkansas', value: 'ARK' },
      { label: 'Auburn', value: 'AUB' },
      { label: 'Florida', value: 'FLA' },
      { label: 'Georgia', value: 'UGA' },
      { label: 'Kentucky', value: 'UK' },
      { label: 'LSU', value: 'LSU' },
      { label: 'Ole Miss', value: 'MISS' },
      { label: 'Mississippi State', value: 'MSST' },
      { label: 'Missouri', value: 'MIZZ' },
      { label: 'South Carolina', value: 'SC' },
      { label: 'Tennessee', value: 'TENN' },
      { label: 'Texas A&M', value: 'TAMU' },
      { label: 'Vanderbilt', value: 'VAN' },
      { label: 'BYU', value: 'BYU' },
      { label: 'Army', value: 'ARMY' },
      { label: 'UMass', value: 'UMASS' },
      { label: 'Notre Dame', value: 'ND' },
      { label: 'Cincinnati', value: 'CIN' },
      { label: 'UConn', value: 'CONN' },
      { label: 'ECU', value: 'ECU' },
      { label: 'Houston', value: 'HOU' },
      { label: 'Memphis', value: 'MEM' },
      { label: 'Navy', value: 'NAVY' },
      { label: 'SMU', value: 'SMU' },
      { label: 'South Florida', value: 'USF' },
      { label: 'Temple', value: 'TEM' },
      { label: 'Tulane', value: 'TULN' },
      { label: 'Tulsa', value: 'TLSA' },
      { label: 'UCF', value: 'UCF' },
      { label: 'Charlotte', value: 'CHAR' },
      { label: 'FAU', value: 'FAU' },
      { label: 'FIU', value: 'FIU' },
      { label: 'Louisiana Tech', value: 'LT' },
      { label: 'Marshall', value: 'MRSH' },
      { label: 'Middle Tennessee', value: 'MTSU' },
      { label: 'North Texas', value: 'UNT' },
      { label: 'Old Dominion', value: 'ODU' },
      { label: 'Rice', value: 'RICE' },
      { label: 'Southern Miss', value: 'USM' },
      { label: 'UTEP', value: 'UTEP' },
      { label: 'UTSA', value: 'UTSA' },
      { label: 'WKU', value: 'WKU' },
      { label: 'Akron', value: 'AKR' },
      { label: 'Ball State', value: 'BALL' },
      { label: 'Bowling Green', value: 'BGSU' },
      { label: 'Buffalo', value: 'BUFF' },
      { label: 'Central Michigan', value: 'CMU' },
      { label: 'Eastern Michigan', value: 'EMU' },
      { label: 'Kent State', value: 'KENT' },
      { label: 'Miami (OH)', value: 'M-OH' },
      { label: 'Northern Illinois', value: 'NIU' },
      { label: 'Ohio', value: 'OHIO' },
      { label: 'Toledo', value: 'TOL' },
      { label: 'Western Michigan', value: 'WMU' },
      { label: 'Air Force', value: 'AFA' },
      { label: 'Boise State', value: 'BSU' },
      { label: 'Colorado State', value: 'CSU' },
      { label: 'Fresno State', value: 'FRES' },
      { label: 'Hawaii', value: 'HAW' },
      { label: 'Nevada', value: 'NEV' },
      { label: 'New Mexico', value: 'UNM' },
      { label: 'San Diego State', value: 'SDSU' },
      { label: 'San José State', value: 'SJSU' },
      { label: 'UNLV', value: 'UNLV' },
      { label: 'Utah State', value: 'USU' },
      { label: 'Wyoming', value: 'WYO' },
      { label: 'Appalachian State', value: 'APP' },
      { label: 'Arkansas State', value: 'ARST' },
      { label: 'Georgia Southern', value: 'GASO' },
      { label: 'Georgia State', value: 'GAST' },
      { label: 'Idaho', value: 'IDHO' },
      { label: 'Louisiana Lafayette', value: 'ULL' },
      { label: 'Louisiana Monroe', value: 'ULM' },
      { label: 'New Mexico State', value: 'NMSU' },
      { label: 'South Alabama', value: 'USA' },
      { label: 'Texas State', value: 'TXST' },
      { label: 'Troy', value: 'TROY' },
      { label: 'Big Sky', value: 'Big Sky' },
      { label: 'Cal Poly', value: 'CP' },
      { label: 'Eastern Washington', value: 'EWU' },
      { label: 'Idaho State', value: 'IDST' },
      { label: 'Montana', value: 'MONT' },
      { label: 'Montana State', value: 'MTST' },
      { label: 'North Dakota', value: 'UND' },
      { label: 'Northern Arizona', value: 'NAU' },
      { label: 'Northern Colorado', value: 'UNCO' },
      { label: 'Portland State', value: 'PRST' },
      { label: 'Sacramento State', value: 'SAC' },
      { label: 'Southern Utah', value: 'SUU' },
      { label: 'UC Davis', value: 'UCD' },
      { label: 'Weber State', value: 'WEB' },
      { label: 'Big South', value: 'Big South' },
      { label: 'Charleston Southern', value: 'CHSO' },
      { label: 'Coastal Carolina', value: 'CCAR' },
      { label: 'Gardner-Webb', value: 'WEBB' },
      { label: 'Kennesaw State', value: 'KENN' },
      { label: 'Liberty', value: 'LIB' },
      { label: 'Monmouth', value: 'MONM' },
      { label: 'Presbyterian', value: 'PRE' },
      { label: 'Albany', value: 'ALBY' },
      { label: 'Delaware', value: 'DEL' },
      { label: 'Elon', value: 'ELON' },
      { label: 'James Madison', value: 'JMU' },
      { label: 'Maine', value: 'MAINE' },
      { label: 'New Hampshire', value: 'UNH' },
      { label: 'Rhode Island', value: 'URI' },
      { label: 'Richmond', value: 'RICH' },
      { label: 'Stony Brook', value: 'STON' },
      { label: 'Towson', value: 'TOWS' },
      { label: 'Villanova', value: 'NOVA' },
      { label: 'William & Mary', value: 'W&M' },
      { label: 'Ivy League', value: 'Ivy' },
      { label: 'Brown', value: 'BRWN' },
      { label: 'Cornell', value: 'COR' },
      { label: 'Columbia', value: 'CLMB' },
      { label: 'Dartmouth', value: 'DART' },
      { label: 'Harvard', value: 'HARV' },
      { label: 'UPenn', value: 'PENN' },
      { label: 'Princeton', value: 'PRIN' },
      { label: 'Yale', value: 'YALE' },
      { label: 'Bethune-Cookman', value: 'COOK' },
      { label: 'Delaware State', value: 'DSU' },
      { label: 'Florida A&M', value: 'FAMU' },
      { label: 'Hampton', value: 'HAMP' },
      { label: 'Howard', value: 'HOW' },
      { label: 'Morgan State', value: 'MORG' },
      { label: 'Norfolk State', value: 'NORF' },
      { label: 'North Carolina A&T', value: 'NCAT' },
      { label: 'NC Central', value: 'NCCU' },
      { label: 'Savannah State', value: 'SAV' },
      { label: 'South Carolina State', value: 'SCST' },
      { label: 'Missouri Valley', value: 'MVFC' },
      { label: 'Illinois State', value: 'ILST' },
      { label: 'Indiana State', value: 'INST' },
      { label: 'Missouri State', value: 'MOST' },
      { label: 'North Dakota State', value: 'NDSU' },
      { label: 'Northern Iowa', value: 'UNI' },
      { label: 'South Dakota', value: 'SDAK' },
      { label: 'South Dakota State', value: 'SDSU' },
      { label: 'Southern Illinois', value: 'SIU' },
      { label: 'Western Illinois', value: 'WIU' },
      { label: 'Youngstown State', value: 'YSU' },
      { label: 'Northeast', value: 'NEC' },
      { label: 'Bryant', value: 'BRY' },
      { label: 'Central Connecticut', value: 'CCSU' },
      { label: 'Duquesne', value: 'DUQ' },
      { label: 'Robert Morris (PA)', value: 'RMU' },
      { label: 'Sacred Heart', value: 'SHU' },
      { label: 'St. Francis (PA)', value: 'SFU' },
      { label: 'Wagner', value: 'WAG' },
      { label: 'Ohio Valley', value: 'OVC' },
      { label: 'Austin Peay', value: 'PEAY' },
      { label: 'Eastern Illinois', value: 'EIU' },
      { label: 'Eastern Kentucky', value: 'EKY' },
      { label: 'Jacksonville State', value: 'JVST' },
      { label: 'Murray State', value: 'MURR' },
      { label: 'Southeast Missouri', value: 'SEMO' },
      { label: 'Tennessee State', value: 'TNST' },
      { label: 'Tennessee Tech', value: 'TNTC' },
      { label: 'Tennessee-Martin', value: 'UTM' },
      { label: 'Patriot', value: 'Patriot' },
      { label: 'Bucknell', value: 'BUCK' },
      { label: 'Colgate', value: 'COLG' },
      { label: 'Fordham', value: 'FOR' },
      { label: 'Georgetown', value: 'GTWN' },
      { label: 'Holy Cross', value: 'HC' },
      { label: 'Lafayette', value: 'LAF' },
      { label: 'Lehigh', value: 'LEH' },
      { label: 'Pioneer', value: 'Pioneer' },
      { label: 'Butler', value: 'BUT' },
      { label: 'Campbell', value: 'CAMP' },
      { label: 'Davidson', value: 'DAV' },
      { label: 'Dayton', value: 'DAY' },
      { label: 'Drake', value: 'DRKE' },
      { label: 'Jacksonville', value: 'JAC' },
      { label: 'Marist', value: 'MRST' },
      { label: 'Morehead State', value: 'MORE' },
      { label: 'San Diego', value: 'USD' },
      { label: 'Stetson', value: 'STET' },
      { label: 'Valparaiso', value: 'VALP' },
      { label: 'SoCon', value: 'SoCon' },
      { label: 'Chattanooga', value: 'CHAT' },
      { label: 'Furman', value: 'FUR' },
      { label: 'Mercer', value: 'MER' },
      { label: 'Samford', value: 'SAM' },
      { label: 'The Citadel', value: 'CIT' },
      { label: 'Western Carolina', value: 'WCU' },
      { label: 'Wofford', value: 'WOF' },
      { label: 'Southland', value: 'Southland' },
      { label: 'Abilene Christian', value: 'ACU' },
      { label: 'Central Arkansas', value: 'UCA' },
      { label: 'Houston Baptist', value: 'HBU' },
      { label: 'Incarnate Word', value: 'IW' },
      { label: 'Lamar', value: 'LAM' },
      { label: 'McNeese State', value: 'MCNS' },
      { label: 'Nicholls State', value: 'NICH' },
      { label: 'Northwestern State', value: 'NWST' },
      { label: 'Sam Houston State', value: 'SHSU' },
      { label: 'Southeastern Louisiana', value: 'SELA' },
      { label: 'Stephen F. Austin', value: 'SFA' },
      { label: 'Alabama A&M', value: 'AAMU' },
      { label: 'Alabama State', value: 'ALST' },
      { label: 'Alcorn State', value: 'ALCN' },
      { label: 'Arkansas-Pine Bluff', value: 'ARPB' },
      { label: 'Grambling State', value: 'GRAM' },
      { label: 'Jackson State', value: 'JKST' },
      { label: 'Mississippi Valley State', value: 'MVSU' },
      { label: 'Prairie View A&M', value: 'PV' },
      { label: 'Southern University', value: 'SOU' },
      { label: 'Texas Southern', value: 'TXSO' },
    ],
  };

  const favoriteMLSTeamsSetting: SettingsMultiSelect = {
    label: 'Favorite MLS Teams',
    description: 'Select your favorite MLS teams.',
    value: [],
    type: 'multiselect',
    options: [
      { label: 'Atlanta United', value: 'ATL' },
      { label: 'Austin FC', value: 'ATX' },
      { label: 'CF Montreal', value: 'MTL' },
      { label: 'Charlotte FC', value: 'CLT' },
      { label: 'Chicago Fire', value: 'CHI' },
      { label: 'Colorado Rapids', value: 'COL' },
      { label: 'Columbus Crew SC', value: 'CLB' },
      { label: 'D.C. United', value: 'DC' },
      { label: 'FC Cincinnati', value: 'CIN' },
      { label: 'FC Dallas', value: 'DAL' },
      { label: 'Houston Dynamo', value: 'HOU' },
      { label: 'Inter Miami', value: 'MIA' },
      { label: 'Los Angeles FC', value: 'LAN' },
      { label: 'Los Angeles Galaxy', value: 'LA' },
      { label: 'Minnesota United FC', value: 'MIN' },
      { label: 'Nashville SC', value: 'NSH' },
      { label: 'New England Revolution', value: 'NE' },
      { label: 'New York City', value: 'NYC' },
      { label: 'New York Red Bulls', value: 'NYR' },
      { label: 'Orlando City', value: 'ORL' },
      { label: 'Philadelphia Union', value: 'PHI' },
      { label: 'Portland Timbers', value: 'POR' },
      { label: 'Real Salt Lake', value: 'RSL' },
      { label: 'San Jose Earthquakes', value: 'SJ' },
      { label: 'Seattle Sounders', value: 'SEA' },
      { label: 'Sporting Kansas City', value: 'SKC' },
      { label: 'St Louis City SC', value: 'STL' },
      { label: 'Toronto FC', value: 'TOR' },
      { label: 'Vancouver Whitecaps', value: 'VAN' },
    ],
  };

  const favoriteSerieATeamsSetting: SettingsMultiSelect = {
    label: 'Favorite Serie A Teams',
    description: 'Select your favorite Serie A teams.',
    value: [],
    type: 'multiselect',
    options: [
      { label: 'Atalanta', value: 'ATA' },
      { label: 'Bologna', value: 'BOL' },
      { label: 'Cagliari', value: 'CAG' },
      { label: 'Como', value: 'COM' },
      { label: 'Empoli', value: 'EMPO' },
      { label: 'Fiorentina', value: 'FIO' },
      { label: 'Genoa', value: 'GEN' },
      { label: 'Internazionale (Inter)', value: 'INT' },
      { label: 'Juventus', value: 'JUV' },
      { label: 'Lazio', value: 'LAZ' },
      { label: 'Lecce', value: 'LECC' },
      { label: 'Monza', value: 'MON' },
      { label: 'Napoli', value: 'NAP' },
      { label: 'Parma', value: 'PMA' },
      { label: 'Roma', value: 'ROM' },
      { label: 'Salernitana', value: 'SAL' },
      { label: 'Sassuolo', value: 'SAS' },
      { label: 'Torino', value: 'TOR' },
      { label: 'Udinese', value: 'UDI' },
      { label: 'Venezia', value: 'UNIO' },
      { label: 'Verona (Hellas Verona)', value: 'VER' },
      { label: 'AC Milan', value: 'ACM' },
    ],
  };

  const favoriteLaLigaTeamsSetting: SettingsMultiSelect = {
    label: 'Favorite LaLiga Teams',
    description: 'Select your favorite LaLiga teams.',
    value: [],
    type: 'multiselect',
    options: [
      { label: 'Alaves', value: 'ALA' },
      { label: 'Athletic Bilbao', value: 'ATH' },
      { label: 'Atletico Madrid', value: 'ATM' },
      { label: 'Barcelona', value: 'BAR' },
      { label: 'Celta Vigo', value: 'CEL' },
      { label: 'Espanyol', value: 'ESP' },
      { label: 'Getafe', value: 'GET' },
      { label: 'Girona', value: 'GIR' },
      { label: 'Las Palmas', value: 'LPM' },
      { label: 'Leganes', value: 'LEG' },
      { label: 'Osasuna', value: 'OSA' },
      { label: 'Rayo Vallecano', value: 'RAY' },
      { label: 'RCD Mallorca', value: 'MLL' },
      { label: 'Real Betis', value: 'BET' },
      { label: 'Real Madrid', value: 'RMA' },
      { label: 'Real Sociedad', value: 'RSO' },
      { label: 'Sevilla', value: 'SEV' },
      { label: 'Valencia', value: 'VAL' },
      { label: 'Valladolid', value: 'VLD' },
      { label: 'Villarreal', value: 'VIL' },
    ],
  };

  const favoriteChampionsLeagueTeamsSetting: SettingsMultiSelect = {
    label: 'Favorite Champions League Teams',
    description: 'Select your favorite Champions League teams.',
    value: [],
    type: 'multiselect',
    options: [
      { label: 'AC Milan', value: 'MIL' },
      { label: 'Arsenal', value: 'ARS' },
      { label: 'Aston Villa', value: 'AVL' },
      { label: 'Atalanta', value: 'ATA' },
      { label: 'Atletico Madrid', value: 'ATM' },
      { label: 'Barcelona', value: 'BAR' },
      { label: 'Bayer Leverkusen', value: 'LEV' },
      { label: 'Bayern Munich', value: 'FCB' },
      { label: 'Benfica', value: 'SLB' },
      { label: 'Bologna', value: 'BOL' },
      { label: 'Borussia Dortmund', value: 'BVB' },
      { label: 'Brest', value: 'BRE' },
      { label: 'Celtic', value: 'CEL' },
      { label: 'Club Brugge', value: 'CLU' },
      { label: 'FC Red Bull Salzburg', value: 'RBS' },
      { label: 'Feyenoord', value: 'FEY' },
      { label: 'Girona', value: 'GIR' },
      { label: 'GNK Dinamo Zagreb', value: 'DIN' },
      { label: 'Inter Milan', value: 'INT' },
      { label: 'Juventus', value: 'JUV' },
      { label: 'Lille', value: 'LIL' },
      { label: 'Liverpool', value: 'LIV' },
      { label: 'Manchester City', value: 'MCI' },
      { label: 'Monaco', value: 'ASM' },
      { label: 'Paris St Germain', value: 'PSG' },
      { label: 'PSV Eindhoven', value: 'PSV' },
      { label: 'RB Leipzig', value: 'RBL' },
      { label: 'Real Madrid', value: 'RMA' },
      { label: 'Red Star Belgrade', value: 'CZV' },
      { label: 'Shakhtar Donetsk', value: 'SHK' },
      { label: 'Slovan Bratislava', value: 'SLO' },
      { label: 'Sparta Prague', value: 'SPAR' },
      { label: 'Sporting Lisbon', value: 'SPOR' },
      { label: 'Sturm Graz', value: 'STU' },
      { label: 'VfB Stuttgart', value: 'VFB' },
      { label: 'Young Boys', value: 'YB' },
    ],
  };

  const favoritePremierLeagueTeamsSetting: SettingsMultiSelect = {
    label: 'Favorite Premier League Teams',
    description: 'Select your favorite Premier League teams.',
    value: [],
    type: 'multiselect',
    options: [
      { label: 'AFC Bournemouth', value: 'AFC' },
      { label: 'Arsenal', value: 'ARS' },
      { label: 'Aston Villa', value: 'AVL' },
      { label: 'Brentford', value: 'BRE' },
      { label: 'Brighton & Hove Albion', value: 'BHA' },
      { label: 'Chelsea', value: 'CHE' },
      { label: 'Crystal Palace', value: 'CRY' },
      { label: 'Everton', value: 'EVE' },
      { label: 'Fulham', value: 'FUL' },
      { label: 'Ipswich Town', value: 'IPS' },
      { label: 'Leicester City', value: 'LEI' },
      { label: 'Liverpool', value: 'LIV' },
      { label: 'Manchester City', value: 'MCI' },
      { label: 'Manchester United', value: 'MUN' },
      { label: 'Newcastle United', value: 'NEW' },
      { label: 'Nottingham Forest', value: 'NTG' },
      { label: 'Southampton', value: 'SOU' },
      { label: 'Tottenham Hotspur', value: 'TOT' },
      { label: 'West Ham United', value: 'WHU' },
      { label: 'Wolverhampton Wanderers', value: 'WOL' },
    ],
  };

  const favoriteBundesligaTeamsSetting: SettingsMultiSelect = {
    label: 'Favorite Bundesliga Teams',
    description: 'Select your favorite Bundesliga teams.',
    value: [],
    type: 'multiselect',
    options: [
      { label: '1. FC Heidenheim', value: 'FCH' },
      { label: '1. FC Union Berlin', value: 'UNB' },
      { label: '1899 Hoffenheim', value: 'HOF' },
      { label: 'Bayer 04 Leverkusen', value: 'B04' },
      { label: 'Bayern Munich', value: 'FCB' },
      { label: 'Borussia Dortmund', value: 'BVB' },
      { label: 'Borussia Mönchengladbach', value: 'BMG' },
      { label: 'Eintracht Frankfurt', value: 'FFM' },
      { label: 'FC Augsburg', value: 'AUG' },
      { label: 'FC St. Pauli', value: 'PAU' },
      { label: 'Holstein Kiel', value: 'HOLS' },
      { label: 'Mainz 05', value: 'M05' },
      { label: 'RB Leipzig', value: 'RBL' },
      { label: 'SC Freiburg', value: 'SCF' },
      { label: 'VfB Stuttgart', value: 'VFB' },
      { label: 'VfL Bochum', value: 'BOC' },
      { label: 'VfL Wolfsburg', value: 'WOB' },
      { label: 'Werder Bremen', value: 'BRE' },
    ],
  };

  DeskThing.addSettings({
    refreshInterval: refreshIntervalSetting,
    favoriteLeague: favoriteLeagueSetting,
    leaguesToShow: leaguesToShowSetting,
    favoriteNBATeams: favoriteNBATeamsSetting,
    favoriteNFLTeams: favoriteNFLTeamsSetting,
    favoriteNHLTeams: favoriteNHLTeamsSetting,
    favoriteMLBTeams: favoriteMLBTeamsSetting,
    selectedNCAAFTeams: selectedNCAAFTeamsSetting,
    favoriteMLSTeams: favoriteMLSTeamsSetting,
    favoriteSerieATeams: favoriteSerieATeamsSetting,
    favoriteLaLigaTeams: favoriteLaLigaTeamsSetting,
    favoriteChampionsLeagueTeams: favoriteChampionsLeagueTeamsSetting,
    favoritePremierLeagueTeams: favoritePremierLeagueTeamsSetting,
    favoriteBundesligaTeams: favoriteBundesligaTeamsSetting,
  });
};

// Main Entrypoint of the server
DeskThing.on('start', start);
